[package]
name = "scryer-plugin-sdk"
version = "0.12.2"
edition.workspace = true

[dependencies]
base64 = "0.22"
schemars = "1"
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
extism = { workspace = true }
url = "2"
