pub mod builtins;
mod download_client_adapter;
mod indexer_adapter;
mod loader;
mod notification_adapter;
mod socket_host;
mod subtitle_adapter;
mod types;

pub use loader::DynamicDownloadClientPluginProvider;
pub use loader::DynamicNotificationPluginProvider;
pub use loader::DynamicPluginProvider;
pub use loader::DynamicSubtitlePluginProvider;
pub use loader::WasmDownloadClientPluginProvider;
pub use loader::WasmIndexerPluginProvider;
pub use loader::WasmNotificationPluginProvider;
pub use loader::WasmPluginDescriptorLoader;
pub use loader::WasmSubtitlePluginProvider;
pub use loader::build_download_client_plugin_provider;
pub use loader::build_download_client_plugin_provider_from_runtime_plugins;
pub use loader::build_indexer_plugin_provider;
pub use loader::build_indexer_plugin_provider_from_runtime_plugins;
pub use loader::build_notification_plugin_provider;
pub use loader::build_notification_plugin_provider_from_runtime_plugins;
pub use loader::build_subtitle_plugin_provider;
pub use loader::build_subtitle_plugin_provider_from_runtime_plugins;
pub use loader::load_indexer_plugins;
pub use scryer_plugin_sdk::SDK_VERSION;
pub use scryer_plugin_sdk::host_version_matches_constraint;
pub use scryer_plugin_sdk::sdk_constraint_or_legacy;
pub use scryer_plugin_sdk::validate_sdk_contract;
pub use types::{ConfigFieldDef, ConfigFieldOption};
