[package]
name = "scryer-domain"
version = "0.16.6"
edition.workspace = true

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
blake3 = "1"
icu_collator = "2.2"
icu_locale = "2.2"
unicode-normalization = "0.1"
