[package]
name = "scryer-release-parser-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
scryer-release-parser = { path = ".." }

[[bin]]
name = "analyze_release_for_target"
path = "fuzz_targets/analyze_release.rs"
test = false
doc = false
bench = false

[[bin]]
name = "analyze_release_against_targets"
path = "fuzz_targets/analyze_release_with_context.rs"
test = false
doc = false
bench = false

[workspace]
members = []
