name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: upload
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
        required: false
  
  - type: dropdown
    id: installation-type
    attributes:
      label: Installation type
      description: The installation type of your instance
      options:
        - Container
        - Homebrew
        - Binary
    validations:
      required: false
  
  - type: input
    id: installation-version
    attributes:
      label: Srcyer Version
      description: The version of your instance
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g. Windows 11, macOS 14, iOS 17.2, Android 14
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome, Firefox, Safari
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Browser Version
      placeholder: e.g. 124.0
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
