query GetSeries($id: String!, $includeEpisodes: Boolean!, $language: String!) {
  series(id: $id, includeEpisodes: $includeEpisodes, language: $language) {
    series {
      tvdb_id
      name
      sort_name
      slug
      status
      year
      first_aired
      overview
      network
      runtime_minutes
      poster_url
      country
      genres
      aliases
      tagged_aliases {
        name
        language
      }
      artworks {
        kind
        url
      }
      seasons {
        tvdb_id
        number
        label
        episode_type
      }
      episodes {
        tvdb_id
        episode_number
        season_number
        name
        aired
        runtime_minutes
        is_filler
        is_recap
        overview
        absolute_number
        image_url
      }
      anime_mappings {
        mal_id
        mal_dub_id
        anilist_id
        anidb_id
        kitsu_id
        simkl_id
        thetvdb_id
        themoviedb_id
        imdb_id
        trakt_id
        alt_tvdb_id
        thetvdb_season
        thetvdb_part
        score
        anime_media_type
        global_media_type
        status
        mapping_type
        episode_mappings {
          tvdb_season
          episode_start
          episode_end
        }
      }
      anime_movies {
        movie_tvdb_id
        movie_tmdb_id
        movie_imdb_id
        movie_mal_id
        movie_anidb_id
        name
        slug
        year
        content_status
        overview
        poster_url
        language
        runtime_minutes
        sort_title
        imdb_id
        genres
        studio
        digital_release_date
        association_confidence
        continuity_status
        movie_form
        placement
        confidence
        signal_summary
      }
    }
  }
}
