query GetMovie($tvdbId: Int!, $language: String!) {
  movie(tvdbId: $tvdbId, language: $language) {
    movie {
      target_key
      tvdb_id
      name
      slug
      year
      status
      overview
      poster_url
      language
      runtime_minutes
      sort_title
      imdb_id
      tmdb_id
      tmdb_popularity
      anidb_id
      genres
      canonical_tags {
        key
        category
        name
        confidence
        sources
        source_tag_keys
        is_adult
        is_spoiler
      }
      studio
      tmdb_release_date
      artworks {
        kind
        url
      }
    }
  }
}
