/*
 * build-css.mjs — compiles the scryer-web Tailwind v4 stylesheet into a stable,
 * self-contained CSS file for design-sync's cfg.cssEntry.
 *
 * Why this exists: scryer-web is a Vite *app*, not a published component library,
 * so there is no library CSS artifact at a stable path — `vite build` only emits a
 * content-hashed dist/assets/index-*.css. This compiles app/globals.css (the real
 * theme: tokens, [data-slot] rules, @apply base layer) with explicit @source globs
 * that cover both components/ and the authored design-sync previews, so every utility
 * class used by a synced component or its preview is present in the output.
 *
 * Output: .design-sync/.cache/ds.css  (gitignored; regenerated by cfg.buildCmd each sync)
 * Run from the package root:  node .design-sync/build-css.mjs
 */
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..'); // package root (.design-sync's parent)

const entryCss = [
  '@import "./app/globals.css";',
  '@source "./components/**/*.{ts,tsx}";',
  '@source "./src/**/*.{ts,tsx}";',
  '@source "./app/**/*.{ts,tsx}";',
  '@source "./.design-sync/previews/**/*.{ts,tsx}";',
  '',
].join('\n');

// Tailwind resolves @import / @source relative to dirname(from). Write a real entry
// file at the package root so that base is correct, then clean it up.
const entryPath = path.join(root, '.ds-tw-entry.css');
const outDir = path.join(root, '.design-sync', '.cache');
const outPath = path.join(outDir, 'ds.css');

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(entryPath, entryCss);
try {
  const result = await postcss([tailwind()]).process(entryCss, {
    from: entryPath,
    to: outPath,
  });
  fs.writeFileSync(outPath, result.css);
  console.log(`[build-css] wrote ${path.relative(root, outPath)} (${(result.css.length / 1024).toFixed(0)} KB)`);
} finally {
  fs.rmSync(entryPath, { force: true });
}
